Algoritmo "ALG_DIVISIVEIS"
// Lógica de programação
// Agnaldo Ferraz
// Felipe Bonini
// 15/04/2025
Var
n : inteiro

Inicio
escreva ("Escreva um numero inteiro: ")
leia (n)

se (n mod 10=0) entao
escreva (n, " é divisivel por 10, 5 e por 2!")
senao
se (n mod 5=0) entao
escreva (n, " é divisivel por 5!")
senao
se (n mod 2=0) entao
escreva (n, " é divisivel por 2!")
senao
escreva (n, " não é divisivel nem por 10, nem por 5 e nem por 2!")
fimse
fimse
fimse

Fimalgoritmo